# Zadanie 1. Kalkulator trajektorii lotu pocisku

Zaimportuj z moduł `math` następujące funkcje:
* `sin` (nazwij `sinus`) - zwraca wartość funkcji sinus dla kąta podanego w radianach;
* `cos` (nazwij `cosinus`) - zwraca wartość funkcji cosinus dla kąta podanego w radianach;
* `radians` (nazwij `deg_to_rad`) - konwertuje wartość ze stopni na radiany;
* `pow` (nazwij `potega`) - oblicza potęgę ustalonego stopnia.

Program pyta użytkownika o dwie wartości:
* $v$ - prędkość wylotowa pocisku (m/s);
* $\theta$ - kąt wyrzutu pocisku (stopnie).

Następnie program oblicza:
* maksymalną wysokość jaką osiągnie pocisk w trakcie lotu: $h_{max}=\frac{v^2\cdot sin^2(\theta_r)}{2g}$
* czas lotu pocisku: $t=\frac{2v\cdot sin(\theta_r)}{g}$
* zasięg pocisku: $\text{range}=\frac{v^2\cdot sin(2\theta_r)}{g}$

gdzie:
* $g$ - przyspieszenie ziemskie: $g=9.81\space m/s^2$
* $\theta_r$ - kąt wyrzutu pocisku wyrażony w radianach: $\theta_r=\text{deg\_to\_rad} (\theta)$

Program wypisuje wynik na ekran z dokładnością do dwóch miejsc po przecinku i ze stosownym opisem.

In [4]:
from math import sin as sinus
from math import cos as cosinus
from math import radians as deg_to_rad
from math import pow as potega

In [5]:
v = float(input("podaj prędkość wylotową pocisku (m/s): "))
theta = float(input("podaj kąt wyrzutu pocisku (w stopniach): "))
g = 9.81

max = (potega(v, 2) * potega(sinus(deg_to_rad(theta)), 2)) / 2 * g
t = (2 * v * sinus(deg_to_rad(theta))) / g
range = (potega(v, 2) * sinus(2*deg_to_rad(theta))) / g

#TEST

print(max)
print(t)
print(range)

2695.8612472175137
4.779585669593563
263.97790838115634

# Zadanie 2. Analiza sekwencji genetycznych.

Zaimportuj z modułu `random` następujące funkcje:
* `choice` - losuje jedną wartość z podanego zestawu opcji;
* `random` - losuje wartość z przedziału $0-1$.

Zaimplementuj następujące funkcje:
* `generuj_dna(d: int) -> str`: funkcja przyjmuje jako parametr długość sekwencji do wygenerowania i zwraca sekwencję DNA wygenerowaną w sposób losowy opierając się na słowniku znanych nukleotydów;
* `mutuj_dna(sekwencja: str, pr_mut: float) -> str`: funkcja przyjmuje dwa parametry: sekwencja DNA i prawdopodobieństwo mutacji, dokonuje losowych zmian w oryginalnej sekwencji i zwraca sekwencję zmutowaną;
* `podobienstwo(sekwencja1, sekwencja2) -> float`: funkcja jako parametry przyjmuje dwie sekwencje i następnie oblicza liczbę różnic między sekwencjami. Następnie oblicza procentową zawartość różnic w stosunku do długości pierwszej sekwencji i zwraca podobieństwo wyrażone jako $\text{podobieństwo}=1-\frac{\text{liczba różnic}}{\text{długść sekwencji}}$.

Program generuje sekwencję ustalonej długości. Następnie dokonuje mutacji tej sekwencji i oblicza podobieństwo sekwencji oryginalnej do zmutowanej. Na koniec wypisuje na ekran podobieństwo obu sekwencji wyrażone jako wartość procentowa w zaokrągleniu do 2 miejsc po przecinku. Dodatkowo, jeżeli podobieństwo obu sekwencji jest większe niż $97\%$ to program wypisuje na ekran komunikat, że obie sekwencje pochodzą od organizmów tego samego gatunku.

In [1]:
from random import choice
from random import random

In [3]:
#1
def gen_dna(d: int) -> str:
    nukl = ['A', 'C', 'G', 'T']
    seq = ""

    for i in range(d):
        seq += choice(nukl)
    return seq
#2
def mutuj_dna(seq, pr_mut):
    zmutowana = ""
    nukl = ['A', 'C', 'G', 'T']

    for nukld in seq:
        if random() <= pr_mut:
            zmutowana += choice(nukl)
        else:
            zmutowana += nukld
    return zmutowana
#3
def pr_stwo(seq1, seq2):
    roznice = 0

    for i in range(len(seq1)):
        if seq1[i] != seq2[i]:
            roznice += 1
    
    wynik = 1 - (roznice / len(seq1))
    return wynik

og = gen_dna(15)
print(f"sekwencja: {og}")

mut = mutuj_dna(og, 0.3)
print(f"zmutowana sekwencja: {mut}")

p = pr_stwo(og, mut)
proc = round(p *100, 2)
print(f"prawdopodobieństwo tych dwóch sekwencji to {proc}%!")

if p > 0.97:
    print(f"obie sekwencje pochodzą od tego samego gatunku :)")
else:
    print("te sekwencje nie pochodzą od tego samego gatunku")

sekwencja: CAAACTAAGACTCTA
zmutowana sekwencja: CAAACTCAGAGTCAC
prawdopodobieństwo tych dwóch sekwencji to 73.33%!
te sekwencje nie pochodzą od tego samego gatunku

# Zadanie 3. Oczyszczanie metadanych środowiskowych.

Zaimportuj moduł pandas i przypisz mu stosowną nazwę. Wczytaj zestaw danych `data/environmental_metadata.csv`. Jest to zbiór metadanych opisujących próbki pobrane ze środowiska na terenie Polski. Posiada on następujący zestaw cech:
* site: nazwa stanowiska
* season: pora roku, w której pobierana była próba
* depth: głębokość wody z jakiej pobrano próbę, standardowo próbkę pobierano na trzech głębokościach: 20 cm, 50 cm i 80 cm
* molecule: nazwa cząsteczki jaka była izolowana z próbki: DNA lub RNA
* rep_number: numer powtórzenia, każda próba była pobierana 5 razy w 5 różnych miejscach na jednym stanowisku
* latitude: szerokość geograficzna stanowiska
* longitude: długość geograficzna stanowiska
* temperature: temperatura powietrza podczas pobierania próbki
* humidity: wilgotność powietrza podczas pobierania próbki
* particles: średnia liczba cząsteczek stałych w jednym militrze pobranej próbki
* comment: komentarz osoby pobierającej próbę o szczególnych okolicznościach podczas pobierania próbki.

Oczyść dane wykonując następujące kroki:
1. Sprawdź czy zestaw zawiera brakujące dane. Jeżeli tak, użyj metody `.dropna()` aby pozbyć się braków. Zwróć uwagę na to czy należy usunąć wiersze czy kolumny.
2. Sprawdź czy wszystkie zmienne mają taki typ jaki powinny mieć (użyj metody `.info()` na całej tabeli). Jeżeli nie, podmień taką zmienną na przekonwertowaną z użyciem metody `.astype()` na konkretnej kolumnie (serii danych).
3. Przeszukaj zbiór pod kątem niepoprawnych wartości analizując wartości zmiennych merytorycznie, np. szerokość geograficzna obejmuje wartości z przedziału od $-90^o$ do $+90^o$. Wykorzystaj do tego analizę podstawowych statystyk (metoda `.describe()`).
4. Usuń zidentyfikowane niepoprawne wiersze ze zbioru.

Sprawdź ile wierszy i ile kolumn zostało usuniętych ze zbioru. Wynikowy zestaw danych zapisz do pliku `data/environmental_metadata_clean.csv`.

In [ ]:
import pandas as pd
env = pd.read_csv("data/environmental_metadata.csv")

In [35]:
env.head()

,site,season,depth,molecule,rep_number,latitude,longitude,temperature,humidity,particles,comment
16,stanowisko_1,spring,80.0,DNA,3.0,50.504714,15.996064,16.0,75.0,529.880535,Wysoki współczynnik bytności ludzkiej
17,stanowisko_1,spring,80.0,RNA,3.0,50.504714,15.996064,16.0,75.0,671.760093,Wysoki współczynnik bytności ludzkiej
52,stanowisko_1,summer,80.0,DNA,4.0,50.504714,15.996064,28.0,18.0,795.997785,Wysoki współczynnik bytności ludzkiej
53,stanowisko_1,summer,80.0,RNA,4.0,50.504714,15.996064,28.0,18.0,529.467022,Wysoki współczynnik bytności ludzkiej
76,stanowisko_1,autumn,80.0,DNA,3.0,50.504714,15.996064,16.0,73.0,472.159762,"Nie można pobrać próby, woda zbyt płytka. Pobi..."

In [29]:
env.isna().sum()

site              2
season            4
depth             1
molecule          1
rep_number        0
latitude          1
longitude         2
temperature       0
humidity          2
particles         1
comment        1494
dtype: int64

In [57]:
env.dropna(inplace=True)

In [72]:
env = env.reset_index(drop=True)

In [ ]:
env["rep_number"] = env["rep_number"].astype(int)

In [74]:
env.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   site         36 non-null     str
 1   season       36 non-null     str
 2   depth        36 non-null     float64
 3   molecule     36 non-null     str
 4   rep_number   36 non-null     int64
 5   latitude     36 non-null     float64
 6   longitude    36 non-null     float64
 7   temperature  36 non-null     float64
 8   humidity     36 non-null     float64
 9   particles    36 non-null     float64
 10  comment      36 non-null     str
dtypes: float64(6), int64(1), str(4)
memory usage: 3.2 KB

In [75]:
env.describe()

,depth,rep_number,latitude,longitude,temperature,humidity,particles
count,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000
mean,61.666667,3.166667,51.071771,19.007028,17.500000,68.333333,502.096573
std,22.990681,1.230563,1.180817,2.715585,10.729133,25.325312,265.643066
min,20.000000,1.000000,50.031419,15.356903,-1.000000,18.000000,-133.656123
25%,50.000000,2.000000,50.361148,15.996064,10.000000,57.000000,320.925005
50%,80.000000,3.000000,50.522689,18.862614,16.000000,71.500000,529.673779
75%,80.000000,4.000000,51.240101,22.156964,28.000000,85.000000,690.535517
max,80.000000,5.000000,53.528174,22.822394,33.000000,104.000000,997.932644

In [78]:
env["particles"] #12 i 26 na minusie
env["latitude"]
env["longitude"]

0     15.996064
1     15.996064
2     15.996064
3     15.996064
4     15.996064
5     15.996064
6     22.156964
7     22.156964
8     22.156964
9     22.156964
10    16.918580
11    16.918580
12    16.918580
13    16.918580
14    19.785438
15    19.785438
16    20.985179
17    20.985179
18    18.091805
19    18.091805
20    18.091805
21    18.091805
22    22.822394
23    22.822394
24    22.355054
25    22.355054
26    22.355054
27    22.355054
28    21.018274
29    21.018274
30    15.491900
31    15.491900
32    15.356903
33    15.356903
34    19.633423
35    19.633423
Name: longitude, dtype: float64

In [84]:
env.drop([12, 26], inplace=True)

In [90]:
env = env.reset_index(drop=True)

In [91]:
env.info() #34 wiersze, 11 kolumn

<class 'pandas.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   site         34 non-null     str
 1   season       34 non-null     str
 2   depth        34 non-null     float64
 3   molecule     34 non-null     str
 4   rep_number   34 non-null     int64
 5   latitude     34 non-null     float64
 6   longitude    34 non-null     float64
 7   temperature  34 non-null     float64
 8   humidity     34 non-null     float64
 9   particles    34 non-null     float64
 10  comment      34 non-null     str
dtypes: float64(6), int64(1), str(4)
memory usage: 3.1 KB

In [93]:
og = pd.read_csv("data/environmental_metadata.csv")

In [94]:
og.info() #1530 wierszy, 11 kolumn

<class 'pandas.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   site         1528 non-null   str
 1   season       1526 non-null   str
 2   depth        1529 non-null   float64
 3   molecule     1529 non-null   str
 4   rep_number   1530 non-null   float64
 5   latitude     1529 non-null   float64
 6   longitude    1528 non-null   float64
 7   temperature  1530 non-null   float64
 8   humidity     1528 non-null   float64
 9   particles    1529 non-null   float64
 10  comment      36 non-null     str
dtypes: float64(7), str(4)
memory usage: 131.6 KB

In [95]:
wow = 1530 - 34
print(f"zostalo usuniete {wow} wieszy")

zostalo usuniete 1496 wieszy

In [96]:
env.to_csv("data/environmental_metadata_clean.csv")

# Zadanie 4. Grupowanie i agregacja danych.

Wczytaj oczyszczony zestaw danych `data/environmental_metadata_clean.csv`. 
1. Zbadaj ile powtórzeń każdej próby pozostało w zbiorze dla każdego stanowiska, w każdym sezonie, z każdej głębokości i dla każdej molekuły. 
2. Oblicz średnią temperaturę i wilgotność jaka panowała w momencie poboru prób na każdym stanowisku w każdej porze roku.
3. Sprawdź ile średnio cząsteczek występowało w próbce na jesień, na głębokości 50 cm na stanowisku trzecim i czwartym.

In [99]:
clean_env = pd.read_csv("data/environmental_metadata_clean.csv")

In [100]:
clean_env.head()

,Unnamed: 0,site,season,depth,molecule,rep_number,latitude,longitude,temperature,humidity,particles,comment
0,0,stanowisko_1,spring,80.0,DNA,3,50.504714,15.996064,16.0,75.0,529.880535,Wysoki współczynnik bytności ludzkiej
1,1,stanowisko_1,spring,80.0,RNA,3,50.504714,15.996064,16.0,75.0,671.760093,Wysoki współczynnik bytności ludzkiej
2,2,stanowisko_1,summer,80.0,DNA,4,50.504714,15.996064,28.0,18.0,795.997785,Wysoki współczynnik bytności ludzkiej
3,3,stanowisko_1,summer,80.0,RNA,4,50.504714,15.996064,28.0,18.0,529.467022,Wysoki współczynnik bytności ludzkiej
4,4,stanowisko_1,autumn,80.0,DNA,3,50.504714,15.996064,16.0,73.0,472.159762,"Nie można pobrać próby, woda zbyt płytka. Pobi..."

In [116]:
rep = clean_env.groupby(["site", "season", "depth", "molecule"])["rep_number"].count()
print(f'''ilość powtorzeń: 
      {rep}''')

ilość powtorzeń:
      site           season  depth  molecule
stanowisko_1   autumn  80.0   DNA         1
                              RNA         1
               spring  80.0   DNA         1
                              RNA         1
               summer  80.0   DNA         1
                              RNA         1
stanowisko_11  autumn  50.0   RNA         1
               spring  50.0   DNA         1
                              RNA         1
stanowisko_12  spring  50.0   DNA         1
                              RNA         1
stanowisko_14  autumn  80.0   DNA         1
                              RNA         1
stanowisko_15  spring  80.0   DNA         1
                              RNA         1
stanowisko_16  spring  50.0   DNA         1
                              RNA         1
stanowisko_3   spring  20.0   DNA         1
                              RNA         1
               summer  20.0   DNA         1
                              RNA         1
stanowisko_4   autumn  50.0   DNA         1
                              RNA         1
                       80.0   RNA         1
stanowisko_5   summer  80.0   DNA         1
                              RNA         1
stanowisko_7   autumn  80.0   DNA         1
                              RNA         1
stanowisko_8   summer  80.0   DNA         2
                              RNA         2
stanowisko_9   summer  20.0   DNA         1
                              RNA         1
Name: rep_number, dtype: int64

In [122]:
clean_env.groupby(["season", "site"])[["temperature", "humidity"]].mean()

                      temperature  humidity
season site
autumn stanowisko_1     16.000000      73.0
       stanowisko_11    16.000000      65.0
       stanowisko_14     5.000000      39.0
       stanowisko_4      0.333333      99.0
       stanowisko_7     13.000000      74.0
spring stanowisko_1     16.000000      75.0
       stanowisko_11    10.000000      70.0
       stanowisko_12     6.000000      85.0
       stanowisko_15    24.000000      62.0
       stanowisko_16    10.000000      57.0
       stanowisko_3     21.000000      33.0
summer stanowisko_1     28.000000      18.0
       stanowisko_3     30.000000      83.0
       stanowisko_5     33.000000      66.0
       stanowisko_8     27.500000     101.0
       stanowisko_9     32.000000      28.0

In [ ]:
sos = (clean_env["season"] == "autumn") & (clean_env["depth"] == 50.0) & (clean_env["site"].isin(["stanowisko_3", "stanowisko_4"]))

avg_prt = env[sos]["particles"].mean().round(2)
print(f"średnia liczba cząsteczek (jesień, 50cm, dla stanowisk 3 i 4): {avg_prt}")

średnia liczba cząsteczek (jesień, 50cm, dla stanowisk 3 i 4): 355.84

# Zadanie 5. Filtrowanie danych

Wczytaj zestaw danych `data/environmental_metadata_clean.csv`.

1. Wybierz z zestawu tylko próbki pobrane na stanowiskach na północ od Łodzi.
2. Wybierz z zestawu tylko próbki pobrane wiosną i jesienią.

In [141]:
boat = 51.75
nboat = clean_env[clean_env["latitude"] > boat] #na polnoc to wyzsza szerokosc geo

print(f"liczba próbek na północ od Łodzi: {len(nboat)}")

nboat.head()

liczba próbek na północ od Łodzi: 8

,Unnamed: 0,site,season,depth,molecule,rep_number,latitude,longitude,temperature,humidity,particles,comment
17,17,stanowisko_8,summer,80.0,DNA,2,53.528174,18.091805,28.0,104.0,877.498177,"Nie można pobrać próby, woda zbyt płytka. Pobi..."
18,18,stanowisko_8,summer,80.0,RNA,2,53.528174,18.091805,28.0,104.0,421.683918,"Nie można pobrać próby, woda zbyt płytka. Pobi..."
19,19,stanowisko_8,summer,80.0,DNA,5,53.528174,18.091805,27.0,98.0,731.325548,Woda bardzo brudna
20,20,stanowisko_8,summer,80.0,RNA,5,53.528174,18.091805,27.0,98.0,770.957949,Woda bardzo brudna
28,28,stanowisko_14,autumn,80.0,DNA,5,52.314923,15.491900,5.0,39.0,169.378762,Wysoki współczynnik bytności ludzkiej

In [148]:
spr_aut = (clean_env["season"]).isin(["autumn", "spring"])

clean_env[spr_aut]

,Unnamed: 0,site,season,depth,molecule,rep_number,latitude,longitude,temperature,humidity,particles,comment
0,0,stanowisko_1,spring,80.0,DNA,3,50.504714,15.996064,16.0,75.0,529.880535,Wysoki współczynnik bytności ludzkiej
1,1,stanowisko_1,spring,80.0,RNA,3,50.504714,15.996064,16.0,75.0,671.760093,Wysoki współczynnik bytności ludzkiej
4,4,stanowisko_1,autumn,80.0,DNA,3,50.504714,15.996064,16.0,73.0,472.159762,"Nie można pobrać próby, woda zbyt płytka. Pobi..."
5,5,stanowisko_1,autumn,80.0,RNA,3,50.504714,15.996064,16.0,73.0,274.539212,"Nie można pobrać próby, woda zbyt płytka. Pobi..."
6,6,stanowisko_3,spring,20.0,DNA,3,50.206288,22.156964,21.0,33.0,698.927847,Woda bardzo brudna
7,7,stanowisko_3,spring,20.0,RNA,3,50.206288,22.156964,21.0,33.0,524.221000,Woda bardzo brudna
10,10,stanowisko_4,autumn,50.0,DNA,3,50.611826,16.918580,1.0,97.0,664.503458,Wysoki współczynnik bytności ludzkiej
11,11,stanowisko_4,autumn,50.0,RNA,3,50.611826,16.918580,1.0,97.0,47.175201,Wysoki współczynnik bytności ludzkiej
12,12,stanowisko_4,autumn,80.0,RNA,4,50.611826,16.918580,-1.0,103.0,321.265874,"Nie można pobrać próby, woda zbyt płytka. Pobi..."
15,15,stanowisko_7,autumn,80.0,DNA,2,51.240101,20.985179,13.0,74.0,793.633956,"Nie można pobrać próby, woda zbyt płytka. Pobi..."
16,16,stanowisko_7,autumn,80.0,RNA,2,51.240101,20.985179,13.0,74.0,118.290678,"Nie można pobrać próby, woda zbyt płytka. Pobi..."
23,23,stanowisko_11,spring,50.0,DNA,1,50.031419,22.355054,10.0,70.0,522.965552,Woda bardzo brudna
24,24,stanowisko_11,spring,50.0,RNA,1,50.031419,22.355054,10.0,70.0,677.018299,Woda bardzo brudna
25,25,stanowisko_11,autumn,50.0,RNA,2,50.031419,22.355054,16.0,65.0,444.801901,Woda bardzo brudna
26,26,stanowisko_12,spring,50.0,DNA,3,50.495824,21.018274,6.0,85.0,655.659911,Woda bardzo brudna
27,27,stanowisko_12,spring,50.0,RNA,3,50.495824,21.018274,6.0,85.0,453.326281,Woda bardzo brudna
28,28,stanowisko_14,autumn,80.0,DNA,5,52.314923,15.491900,5.0,39.0,169.378762,Wysoki współczynnik bytności ludzkiej
29,29,stanowisko_14,autumn,80.0,RNA,5,52.314923,15.491900,5.0,39.0,337.483662,Wysoki współczynnik bytności ludzkiej
30,30,stanowisko_15,spring,80.0,DNA,5,50.361148,15.356903,24.0,62.0,731.086063,"Nie można pobrać próby, woda zbyt płytka. Pobi..."
31,31,stanowisko_15,spring,80.0,RNA,5,50.361148,15.356903,24.0,62.0,305.440108,"Nie można pobrać próby, woda zbyt płytka. Pobi..."
32,32,stanowisko_16,spring,50.0,DNA,4,53.204200,19.633423,10.0,57.0,997.932644,Woda bardzo brudna
33,33,stanowisko_16,spring,50.0,RNA,4,53.204200,19.633423,10.0,57.0,740.122765,Woda bardzo brudna

# Zadanie 6. Analiza porównawcza

Odnieś się do podzbiorów danych uzyskanych w poprzednim zadaniu i wykonaj poniższe polecenia:
1. Z podzbioru stanowisk z północnej Polski wyodrębnionych w poprzednim zadaniu oblicz średnią temperaturę o każdej zbadanej porze roku. Oblicz to samo dla pozostałych stanowisk. Odpowiedz czy średnia temperatura na północy Polski jest widocznie wyższa niż na południu.
2. Z podzbioru prób zebranych wiosną i jesienią wyodrębnionych w poprzednim zadaniu oblicz średnią temperaturę i średnią wilgotność dla każdego stanowiska. Wykonaj zestawienie tych wartości z danymi dla całego roku. Oblicz różnicę tych wartości i odpowiedz czy istnieje wyraźny trend dla temperatury i wilgotności w chłodniejszych porach roku w stosunku do całego roku.
3. Sprawdź czy istnieje różnica w liczbie cząsteczek w wodzie w próbach pobranych wiosną i jesienią w stosunku do prób pobranych latem. Zbadaj trend dla poszczególnych głębokości.

In [ ]:
nbtemp = nboat.groupby(["season"])["temperature"].mean()
print(f'''średnie temperatury na północy polski: 
{nbtemp}''')

sboat = clean_env[clean_env["latitude"] < boat]
sbtemp = sboat.groupby(["season"])["temperature"].mean()
print(f'''średnie temperatury na południu polski: 
{sbtemp}''')

#średnia temperatura na północy polski jest widocznie niższa niż na południu

średnie temperatury na północy polski:
season
autumn     5.0
spring    10.0
summer    27.5
Name: temperature, dtype: float64
średnie temperatury na południu polski:
season
autumn     9.375
spring    15.400
summer    30.750
Name: temperature, dtype: float64

In [ ]:
mean_spr_aut = clean_env[spr_aut].groupby("site")[["temperature", "humidity"]].mean()

mean_year = clean_env.groupby("site")[["temperature", "humidity"]].mean()

trend = mean_spr_aut - mean_year

print(f'''różnica parametrów:
{trend}''')

#nie można określić dokładnego trendu, 
#na niektórych stanowiskach pomiary były wykonywane tylko na wiosne/ jesien

różnica parametrów:
               temperature   humidity
site
stanowisko_1          -4.0  18.666667
stanowisko_11          0.0   0.000000
stanowisko_12          0.0   0.000000
stanowisko_14          0.0   0.000000
stanowisko_15          0.0   0.000000
stanowisko_16          0.0   0.000000
stanowisko_3          -4.5 -25.000000
stanowisko_4           0.0   0.000000
stanowisko_5           NaN        NaN
stanowisko_7           0.0   0.000000
stanowisko_8           NaN        NaN
stanowisko_9           NaN        NaN

In [162]:
mol_spr_aut = clean_env[spr_aut].groupby("depth")["particles"].mean()
mol_sum = clean_env[clean_env["season"] == "summer"].groupby("depth")["particles"].mean()

mol_trend = mol_spr_aut - mol_sum
print(f'''trend cząsteczek wg głębokości:
{mol_trend}''')

trend cząsteczek wg głębokości:
depth
20.0     68.393949
50.0           NaN
80.0   -191.415045
Name: particles, dtype: float64