# Ćwiczenia 1: Wprowadzenie do analizy danych tabelarycznych

## Zadanie 1.

Zaimportować stałą `pi` z modułu `math`. Obliczyć pole koła o promieniu $r=7$ wykorzystując stałą `pi` z modułu `math`.

In [1]:
import math #import całego modułu
math.pi #odnoszenie się do metod modułu math

3.141592653589793

In [2]:
from math import pi #import danej rzeczy z modułu
pi #wyświetli liczbę pi

3.141592653589793

In [3]:
r = 7 #promień
pi*r**2 #wzór na pole koła

153.93804002589985

## Zadanie 2.

Zaimportować funkcję `randint` z modułu `random` i nazwać ją `losuj_zakres`. Napisać program, który wykorzysta tę funkcję do wylosowania numeru studenta, który pójdzie do tablicy.

In [4]:
import random
random.randint(5,10) #postawienie pytajnika przed funkcją pozwala na wyświetlenie jej dokumentacji

8

In [5]:
from random import randint as losuj_zakres #importowanie jednej funkcji i nadawanie jej nazwy
num_studenta = losuj_zakres(1,11) #w ten sposób nie wystąpi błąd (do tablicy idzie i wstaje ten sam student)
print(f'do tablicy idzie student o numerze {num_studenta}')
print(f'student o numerze {num_studenta} wstaje z krzesła')
#bez przypisania randint(zakres) do jednej zmiennej to funkcja dwa razy wylosuje numery

do tablicy idzie student o numerze 5
student o numerze 5 wstaje z krzesła

## Zadanie 3.

Zaimportować moduł `pandas` i przypisać mu nazwę `pd`. Wypisać wersję aktualnie zainstalowanego modułu Pandas.

In [6]:
pip install pandas

Requirement already satisfied: pandas in /home/oligus/miniconda3/envs/pp/lib/python3.14/site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in /home/oligus/miniconda3/envs/pp/lib/python3.14/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/oligus/miniconda3/envs/pp/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/oligus/miniconda3/envs/pp/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
pd.__version__

'3.0.1'

## Zadanie 4.

Wykorzystując moduł Pandas wczytać zestaw danych gallstone. Wyświetlić krótką próbkę danych metodą `.head()`, opis kolumn metodą `.info()` oraz podstawowe statystki tego zbioru danych metodą `.descrbie()`. Transponuj wynik `.describe()` dla lepszej czytelności.

In [8]:
gallstone = pd.read_csv("DATA/gallstone.csv")

In [9]:
gallstone.head() #wyświetla kilka pierwszych wierszy (parametr n określa ilość wierszy)
#gallstone.tail() wyświetla kilka ostatnich wierszy

,Gallstone Status,Age,Gender,Comorbidity,Coronary Artery Disease (CAD),Hypothyroidism,Hyperlipidemia,Diabetes Mellitus (DM),Height,Weight,...,High Density Lipoprotein (HDL),Triglyceride,Aspartat Aminotransferaz (AST),Alanin Aminotransferaz (ALT),Alkaline Phosphatase (ALP),Creatinine,Glomerular Filtration Rate (GFR),C-Reactive Protein (CRP),Hemoglobin (HGB),Vitamin D
0,0,50,0,0,0,0,0,0,185,92.8,...,40.0,134.0,20.0,22.0,87.0,0.82,112.47,0.0,16.0,33.0
1,0,47,0,1,0,0,0,0,176,94.5,...,43.0,103.0,14.0,13.0,46.0,0.87,107.10,0.0,14.4,25.0
2,0,61,0,0,0,0,0,0,171,91.1,...,43.0,69.0,18.0,14.0,66.0,1.25,65.51,0.0,16.2,30.2
3,0,41,0,0,0,0,0,0,168,67.7,...,59.0,53.0,20.0,12.0,34.0,1.02,94.10,0.0,15.4,35.4
4,0,42,0,0,0,0,0,0,178,89.6,...,30.0,326.0,27.0,54.0,71.0,0.82,112.47,0.0,16.8,40.6

In [10]:
gallstone.info() #wypisuje skompresowane kolumny z pliku, info o typach danych i NA,

<class 'pandas.DataFrame'>
RangeIndex: 319 entries, 0 to 318
Data columns (total 39 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Gallstone Status                                319 non-null    int64
 1   Age                                             319 non-null    int64
 2   Gender                                          319 non-null    int64
 3   Comorbidity                                     319 non-null    int64
 4   Coronary Artery Disease (CAD)                   319 non-null    int64
 5   Hypothyroidism                                  319 non-null    int64
 6   Hyperlipidemia                                  319 non-null    int64
 7   Diabetes Mellitus (DM)                          319 non-null    int64
 8   Height                                          319 non-null    int64
 9   Weight                                          319 non-null    float64
 10  Body Mass Index (BMI)                           319 non-null    float64
 11  Total Body Water (TBW)                          319 non-null    float64
 12  Extracellular Water (ECW)                       319 non-null    float64
 13  Intracellular Water (ICW)                       319 non-null    float64
 14  Extracellular Fluid/Total Body Water (ECF/TBW)  319 non-null    float64
 15  Total Body Fat Ratio (TBFR) (%)                 319 non-null    float64
 16  Lean Mass (LM) (%)                              319 non-null    float64
 17  Body Protein Content (Protein) (%)              319 non-null    float64
 18  Visceral Fat Rating (VFR)                       319 non-null    int64
 19  Bone Mass (BM)                                  319 non-null    float64
 20  Muscle Mass (MM)                                319 non-null    float64
 21  Obesity (%)                                     319 non-null    float64
 22  Total Fat Content (TFC)                         319 non-null    float64
 23  Visceral Fat Area (VFA)                         319 non-null    float64
 24  Visceral Muscle Area (VMA) (Kg)                 319 non-null    float64
 25  Hepatic Fat Accumulation (HFA)                  319 non-null    int64
 26  Glucose                                         319 non-null    float64
 27  Total Cholesterol (TC)                          319 non-null    float64
 28  Low Density Lipoprotein (LDL)                   319 non-null    float64
 29  High Density Lipoprotein (HDL)                  319 non-null    float64
 30  Triglyceride                                    319 non-null    float64
 31  Aspartat Aminotransferaz (AST)                  319 non-null    float64
 32  Alanin Aminotransferaz (ALT)                    319 non-null    float64
 33  Alkaline Phosphatase (ALP)                      319 non-null    float64
 34  Creatinine                                      319 non-null    float64
 35  Glomerular Filtration Rate (GFR)                319 non-null    float64
 36  C-Reactive Protein (CRP)                        319 non-null    float64
 37  Hemoglobin (HGB)                                319 non-null    float64
 38  Vitamin D                                       319 non-null    float64
dtypes: float64(28), int64(11)
memory usage: 97.3 KB

In [11]:
gallstone.describe() #podstawowe statystyki zbioru

,Gallstone Status,Age,Gender,Comorbidity,Coronary Artery Disease (CAD),Hypothyroidism,Hyperlipidemia,Diabetes Mellitus (DM),Height,Weight,...,High Density Lipoprotein (HDL),Triglyceride,Aspartat Aminotransferaz (AST),Alanin Aminotransferaz (ALT),Alkaline Phosphatase (ALP),Creatinine,Glomerular Filtration Rate (GFR),C-Reactive Protein (CRP),Hemoglobin (HGB),Vitamin D
count,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.00000,319.000000,...,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000
mean,0.495298,48.068966,0.492163,0.335423,0.037618,0.028213,0.025078,0.134796,167.15674,80.564890,...,49.475549,144.502163,21.684953,26.855799,73.112539,0.800611,100.818903,1.853856,14.418182,21.401411
std,0.500763,12.114558,0.500724,0.517340,0.190568,0.165841,0.156609,0.342042,10.05303,15.709069,...,17.718701,97.904493,16.697605,27.884413,24.181069,0.176433,16.971396,4.989591,1.775815,9.981659
min,0.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,145.00000,42.900000,...,25.000000,1.390000,8.000000,3.000000,7.000000,0.460000,10.600000,0.000000,8.500000,3.500000
25%,0.000000,38.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,159.50000,69.600000,...,40.000000,83.000000,15.000000,14.250000,58.000000,0.650000,94.170000,0.000000,13.300000,13.250000
50%,0.000000,49.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,168.00000,78.800000,...,46.500000,119.000000,18.000000,19.000000,71.000000,0.790000,104.000000,0.215000,14.400000,22.000000
75%,1.000000,56.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,175.00000,91.250000,...,56.000000,172.000000,23.000000,30.000000,86.000000,0.920000,110.745000,1.615000,15.700000,28.060000
max,1.000000,96.000000,1.000000,3.000000,1.000000,1.000000,1.000000,1.000000,191.00000,143.500000,...,273.000000,838.000000,195.000000,372.000000,197.000000,1.460000,132.000000,43.400000,18.800000,53.100000

In [12]:
gallstone.describe().T #inny sposob na transpozycję tabeli

,count,mean,std,min,25%,50%,75%,max
Gallstone Status,319.0,0.495298,0.500763,0.00,0.000,0.000000,1.000,1.00
Age,319.0,48.068966,12.114558,20.00,38.500,49.000000,56.000,96.00
Gender,319.0,0.492163,0.500724,0.00,0.000,0.000000,1.000,1.00
Comorbidity,319.0,0.335423,0.517340,0.00,0.000,0.000000,1.000,3.00
Coronary Artery Disease (CAD),319.0,0.037618,0.190568,0.00,0.000,0.000000,0.000,1.00
Hypothyroidism,319.0,0.028213,0.165841,0.00,0.000,0.000000,0.000,1.00
Hyperlipidemia,319.0,0.025078,0.156609,0.00,0.000,0.000000,0.000,1.00
Diabetes Mellitus (DM),319.0,0.134796,0.342042,0.00,0.000,0.000000,0.000,1.00
Height,319.0,167.156740,10.053030,145.00,159.500,168.000000,175.000,191.00
Weight,319.0,80.564890,15.709069,42.90,69.600,78.800000,91.250,143.50
Body Mass Index (BMI),319.0,28.877116,5.313707,17.40,25.250,28.300000,31.850,49.70
Total Body Water (TBW),319.0,40.587774,7.930235,13.00,34.200,39.800000,47.000,66.20
Extracellular Water (ECW),319.0,17.071160,3.161857,9.00,14.800,17.100000,19.400,27.80
Intracellular Water (ICW),319.0,23.634483,5.349332,13.80,19.300,23.000000,27.550,57.10
Extracellular Fluid/Total Body Water (ECF/TBW),319.0,42.212038,3.244470,29.23,40.075,42.000000,44.000,52.00
Total Body Fat Ratio (TBFR) (%),319.0,28.274984,8.444417,6.30,22.025,27.820000,34.810,50.92
Lean Mass (LM) (%),319.0,71.638245,8.437598,48.99,65.165,72.110000,77.850,93.67
Body Protein Content (Protein) (%),319.0,15.938809,2.334744,5.56,14.465,15.870000,17.430,24.81
Visceral Fat Rating (VFR),319.0,9.078370,4.332501,1.00,6.000,9.000000,12.000,31.00
Bone Mass (BM),319.0,2.803292,0.509467,1.40,2.400,2.800000,3.200,4.00
Muscle Mass (MM),319.0,54.273041,10.603833,4.70,45.800,53.900000,62.600,78.80
Obesity (%),319.0,35.850125,109.799718,0.40,13.900,25.600000,41.750,1954.00
Total Fat Content (TFC),319.0,23.487774,9.607607,3.10,17.000,22.600000,28.550,62.50
Visceral Fat Area (VFA),319.0,12.171599,5.262178,0.90,8.570,11.590000,15.100,41.00
Visceral Muscle Area (VMA) (Kg),319.0,30.403448,4.460530,18.90,27.250,30.408108,33.800,41.10
Hepatic Fat Accumulation (HFA),319.0,1.150470,1.059217,0.00,0.000,1.000000,2.000,4.00
Glucose,319.0,108.688715,44.848714,69.00,92.000,98.000000,109.000,575.00
Total Cholesterol (TC),319.0,203.495298,45.758501,60.00,172.000,198.000000,233.000,360.00
Low Density Lipoprotein (LDL),319.0,126.652351,38.541175,11.00,100.500,122.000000,151.000,293.00
High Density Lipoprotein (HDL),319.0,49.475549,17.718701,25.00,40.000,46.500000,56.000,273.00
Triglyceride,319.0,144.502163,97.904493,1.39,83.000,119.000000,172.000,838.00
Aspartat Aminotransferaz (AST),319.0,21.684953,16.697605,8.00,15.000,18.000000,23.000,195.00
Alanin Aminotransferaz (ALT),319.0,26.855799,27.884413,3.00,14.250,19.000000,30.000,372.00
Alkaline Phosphatase (ALP),319.0,73.112539,24.181069,7.00,58.000,71.000000,86.000,197.00
Creatinine,319.0,0.800611,0.176433,0.46,0.650,0.790000,0.920,1.46
Glomerular Filtration Rate (GFR),319.0,100.818903,16.971396,10.60,94.170,104.000000,110.745,132.00
C-Reactive Protein (CRP),319.0,1.853856,4.989591,0.00,0.000,0.215000,1.615,43.40
Hemoglobin (HGB),319.0,14.418182,1.775815,8.50,13.300,14.400000,15.700,18.80
Vitamin D,319.0,21.401411,9.981659,3.50,13.250,22.000000,28.060,53.10

## Zadanie 5.

Oczyścić dane z nieprawidłowych wartości:
1. sprawdzić czy wczytany zestaw danych posiada wartości brakujące. Jeśli tak to należy usunąć wiersze zawierające braki.
2. analizując tabelę z powyższego zadania zidentyfikować nieprawidłowy wiersz
3. analizując układ zmiennych dotyczących zawartości wody w organizmie zidentyfikować nieprawidłowe dane $(\text{ECW} + \text{ICW} \approx \text{TBW})$
4. analizując układ zmiennych masy mięśniowej, beztłuszczowej masy ciała i wagi zidentyfikować nieprawidłowe dane
5. korzystając z [wzoru Friedewalda](https://pl.wikipedia.org/wiki/Wz%C3%B3r_Friedewalda): $\text{LDL} \approx \text{TC} − \text{HDL} − \text{TG}/5$ zidentyfikować wiersze o niespójnym profilu lipidowym
6. analizując tabelę z powyższego zadania sprawdź czy na pewno wszystkie wiersze zawierają poprawną wartość triglicerydów.
7. usunąć zidentyfikowane wiersze ze zbioru danych.

In [13]:
#1 - NA
gallstone.isna().sum().sum() #wyświetla kolumny F/T dla brakujących wartości (.sum sumuje wszystkie te wartosci 0-f i 1-p)
#podwojnie zsumowane wyświetla łaczna ilość F(0)
#co zwraca dana metoda  → co mozna jeszcze wywołać na podstawie wyniku

np.int64(0)

In [14]:
#2 - nieprawidłowy wiersz z zadania 4
gallstone["Obesity (%)"].nlargest() #wypisuje daną kolumnę z dataframe
#nlargest pokazuje najwyższą wartość (1954 to wartosc nieprawidłowa)

239    1954.00
23      125.60
209     106.30
280      96.63
246      95.64
Name: Obesity (%), dtype: float64

In [15]:
#3 - zawartość wody nieprawidłowe dane
(gallstone["Extracellular Water (ECW)"] + gallstone["Intracellular Water (ICW)"] - gallstone["Total Body Water (TBW)"]).abs().nlargest()

178    62.6
168    14.7
300    10.0
60      1.0
268     0.5
dtype: float64

In [16]:
#4 - masa mięśniowa, beztłuszczowa masa i waga, nieprawidłowe dane
gallstone["Muscle Mass (MM)"].nsmallest()

205     4.7
261    32.8
135    34.6
300    35.0
233    36.2
Name: Muscle Mass (MM), dtype: float64

In [17]:
#4 - masa mięśniowa, beztłuszczowa masa i waga, nieprawidłowe dane
gallstone.columns #wyświetla nazwy kolumn
gallstone.loc[205,["Muscle Mass (MM)", "Lean Mass (LM) (%)", "Weight"]] #podwójny nawias bo lista i odwołanie do kolumn
#numer miedzy nawiasami mowi o wyswietlanej kolumnie

Muscle Mass (MM)       4.70
Lean Mass (LM) (%)    63.14
Weight                78.40
Name: 205, dtype: float64

In [18]:
#5 - niespójny charakter lipidowy
gallstone.columns
LDL = gallstone["Total Cholesterol (TC)"] - gallstone["High Density Lipoprotein (HDL)"] - gallstone["Triglyceride"]/5
#obliczenie oczekiwanej wartości LDL ze wzoru (tylko returnuje wartość)
(gallstone["Low Density Lipoprotein (LDL)"] - LDL).abs().nlargest(n=10)
#oblicznie różnicy między oczekiwaną a rzeczywistą wartością (wyświetla liste 10 najwiekszych wartości)
gallstone.loc[[194,318],["Total Cholesterol (TC)", "High Density Lipoprotein (HDL)", "Triglyceride", "Low Density Lipoprotein (LDL)"]]
#wyświetlenie kolumn z wartościami o lipidach z wierszy o niespójnym profilu (wybrane manualnie)

,Total Cholesterol (TC),High Density Lipoprotein (HDL),Triglyceride,Low Density Lipoprotein (LDL)
194,280.0,30.0,116.0,88.0
318,296.0,273.0,19.0,155.0

In [19]:
#6 - poprawna wartość triglicerydów (TG =< 400 mg/dL)
gallstone["Triglyceride"].nlargest(n=10)

242    838.0
20     692.0
8      679.0
7      464.0
50     455.0
271    391.0
65     388.0
81     377.0
49     375.0
199    350.0
Name: Triglyceride, dtype: float64

In [20]:
#7 - usunięcie nieprawidłowych wierszy
torev = [139, 23, 209, 178, 168, 300, 205] #panda przyjmuje tylko listę, nie krotki
gallstone.drop(torev) #to jest wynik metody, wiersze nie są usunięte z og tabeli
#można albo przypisać wynik do zmiennej z dataframe lub dodać implace

,Gallstone Status,Age,Gender,Comorbidity,Coronary Artery Disease (CAD),Hypothyroidism,Hyperlipidemia,Diabetes Mellitus (DM),Height,Weight,...,High Density Lipoprotein (HDL),Triglyceride,Aspartat Aminotransferaz (AST),Alanin Aminotransferaz (ALT),Alkaline Phosphatase (ALP),Creatinine,Glomerular Filtration Rate (GFR),C-Reactive Protein (CRP),Hemoglobin (HGB),Vitamin D
0,0,50,0,0,0,0,0,0,185,92.8,...,40.0,134.0,20.0,22.0,87.0,0.82,112.47,0.0,16.0,33.0
1,0,47,0,1,0,0,0,0,176,94.5,...,43.0,103.0,14.0,13.0,46.0,0.87,107.10,0.0,14.4,25.0
2,0,61,0,0,0,0,0,0,171,91.1,...,43.0,69.0,18.0,14.0,66.0,1.25,65.51,0.0,16.2,30.2
3,0,41,0,0,0,0,0,0,168,67.7,...,59.0,53.0,20.0,12.0,34.0,1.02,94.10,0.0,15.4,35.4
4,0,42,0,0,0,0,0,0,178,89.6,...,30.0,326.0,27.0,54.0,71.0,0.82,112.47,0.0,16.8,40.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,1,49,0,0,0,0,0,0,178,88.8,...,55.0,81.0,28.0,50.0,90.0,0.98,94.50,6.2,16.5,8.3
315,1,31,1,0,0,0,0,0,157,53.4,...,58.0,64.0,24.0,16.0,38.0,0.50,128.50,0.0,12.5,24.0
316,1,58,0,0,0,0,0,0,172,96.6,...,45.0,168.0,21.0,27.0,94.0,1.04,83.23,0.0,15.4,15.7
317,1,37,1,0,0,0,0,0,177,88.4,...,33.0,253.0,40.0,22.0,115.0,1.01,98.23,0.4,16.0,33.3
318,1,60,1,0,0,0,0,0,154,63.5,...,273.0,19.0,25.0,73.0,73.0,0.85,73.00,0.0,13.6,29.0

## Zadanie 6.

Obliczyć udział procentowy pacjentów z kamicą nerkową i zdrowych (zmienna *Gallstone Status*). Do zmiennej `kamica` przypisać wiersze pacjentów, którzy mają kamicę $(\text{Gallstone Status}=1)$. Do zmiennej `kontrola` przypisać pacjentów, którzy nie mają kamicy $(\text{Gallstone Status}=0)$.

In [21]:
gallstone["Gallstone Status"].value_counts(normalize=True) *100
#value counts zlicza ilość parametrów, normalize przelicza na ułamek, *100 przelicza na procent
kamica = (gallstone[gallstone["Gallstone Status"] == 1]).count
kontrola = (gallstone[gallstone["Gallstone Status"] == 0]).count

print(f"ilość pacjentów z kamicą: {kamica}")
print(f"ilosć zdrowych pacjentów: {kontrola}")

ilość pacjentów z kamicą: <bound method DataFrame.count of      Gallstone Status  Age  Gender  Comorbidity  \
161                 1   51       0            1
162                 1   62       1            1
163                 1   30       1            0
164                 1   31       1            0
165                 1   40       0            1
..                ...  ...     ...          ...
314                 1   49       0            0
315                 1   31       1            0
316                 1   58       0            0
317                 1   37       1            0
318                 1   60       1            0

     Coronary Artery Disease (CAD)  Hypothyroidism  Hyperlipidemia  \
161                              0               0               0
162                              0               0               0
163                              0               0               0
164                              0               0               0
165                              0               0               0
..                             ...             ...             ...
314                              0               0               0
315                              0               0               0
316                              0               0               0
317                              0               0               0
318                              0               0               0

     Diabetes Mellitus (DM)  Height  Weight  ...  \
161                       1     165    68.2  ...
162                       1     163    83.2  ...
163                       0     160    62.3  ...
164                       0     160    48.9  ...
165                       1     182   110.6  ...
..                      ...     ...     ...  ...
314                       0     178    88.8  ...
315                       0     157    53.4  ...
316                       0     172    96.6  ...
317                       0     177    88.4  ...
318                       0     154    63.5  ...

     High Density Lipoprotein (HDL)  Triglyceride  \
161                            32.0          91.0
162                            44.0         296.0
163                            58.0          52.0
164                            68.0          23.0
165                            42.0         145.0
..                              ...           ...
314                            55.0          81.0
315                            58.0          64.0
316                            45.0         168.0
317                            33.0         253.0
318                           273.0          19.0

     Aspartat Aminotransferaz (AST)  Alanin Aminotransferaz (ALT)  \
161                            14.0                          14.0
162                            16.0                          18.0
163                            16.0                          17.0
164                            16.0                          13.0
165                            17.0                          36.0
..                              ...                           ...
314                            28.0                          50.0
315                            24.0                          16.0
316                            21.0                          27.0
317                            40.0                          22.0
318                            25.0                          73.0

     Alkaline Phosphatase (ALP)  Creatinine  Glomerular Filtration Rate (GFR)  \
161                        86.0        0.73                         89.001333
162                        68.0        0.71                         91.232000
163                        56.0        0.64                         93.462667
164                        54.0        0.59                         95.693333
165                        49.0        0.86                         97.924000
..                          ...         ...                               ...
314                        90.0        0.98                         94.500000
315                        38.0        0.50                        128.500000
316                        94.0        1.04                         83.230000
317                       115.0        1.01                         98.230000
318                        73.0        0.85                         73.000000

     C-Reactive Protein (CRP)  Hemoglobin (HGB)  Vitamin D
161                      1.25              13.9       35.4
162                      4.90              12.9        7.9
163                      0.00              14.0       15.7
164                      0.50              12.4        3.5
165                      3.70              15.7       13.0
..                        ...               ...        ...
314                      6.20              16.5        8.3
315                      0.00              12.5       24.0
316                      0.00              15.4       15.7
317                      0.40              16.0       33.3
318                      0.00              13.6       29.0

[158 rows x 39 columns]>
ilosć zdrowych pacjentów: <bound method DataFrame.count of      Gallstone Status  Age  Gender  Comorbidity  \
0                   0   50       0            0
1                   0   47       0            1
2                   0   61       0            0
3                   0   41       0            0
4                   0   42       0            0
..                ...  ...     ...          ...
156                 0   58       1            0
157                 0   37       1            0
158                 0   49       0            1
159                 0   65       0            1
160                 0   45       0            0

     Coronary Artery Disease (CAD)  Hypothyroidism  Hyperlipidemia  \
0                                0               0               0
1                                0               0               0
2                                0               0               0
3                                0               0               0
4                                0               0               0
..                             ...             ...             ...
156                              0               0               0
157                              0               0               0
158                              0               0               0
159                              0               0               0
160                              0               0               0

     Diabetes Mellitus (DM)  Height  Weight  ...  \
0                         0     185    92.8  ...
1                         0     176    94.5  ...
2                         0     171    91.1  ...
3                         0     168    67.7  ...
4                         0     178    89.6  ...
..                      ...     ...     ...  ...
156                       0     163    66.9  ...
157                       0     168    72.5  ...
158                       1     175   109.7  ...
159                       1     168    65.9  ...
160                       0     172    82.7  ...

     High Density Lipoprotein (HDL)  Triglyceride  \
0                              40.0         134.0
1                              43.0         103.0
2                              43.0          69.0
3                              59.0          53.0
4                              30.0         326.0
..                              ...           ...
156                            46.0         122.0
157                            57.0         149.0
158                            39.0         307.0
159                            38.0         164.0
160                            41.0         103.0

     Aspartat Aminotransferaz (AST)  Alanin Aminotransferaz (ALT)  \
0                              20.0                          22.0
1                              14.0                          13.0
2                              18.0                          14.0
3                              20.0                          12.0
4                              27.0                          54.0
..                              ...                           ...
156                            15.0                          53.0
157                            20.0                           9.0
158                            23.0                          42.0
159                            30.0                          76.0
160                            15.0                          16.0

     Alkaline Phosphatase (ALP)  Creatinine  Glomerular Filtration Rate (GFR)  \
0                          87.0        0.82                        112.470000
1                          46.0        0.87                        107.100000
2                          66.0        1.25                         65.510000
3                          34.0        1.02                         94.100000
4                          71.0        0.82                        112.470000
..                          ...         ...                               ...
156                       101.0        0.65                        101.990000
157                        43.0        0.85                         90.440000
158                        73.0        1.03                         89.050000
159                        86.0        0.99                         84.540000
160                       130.0        0.86                         86.770667

     C-Reactive Protein (CRP)  Hemoglobin (HGB)  Vitamin D
0                         0.0              16.0       33.0
1                         0.0              14.4       25.0
2                         0.0              16.2       30.2
3                         0.0              15.4       35.4
4                         0.0              16.8       40.6
..                        ...               ...        ...
156                       0.0              12.6        4.8
157                       0.0              13.5       19.3
158                       0.0              14.3       20.6
159                       0.1              15.5       19.2
160                       0.0              16.6       35.7

[161 rows x 39 columns]>

In [22]:
kamica = gallstone[gallstone["Gallstone Status"] == 1]
kontrola = gallstone[gallstone["Gallstone Status"] == 0]
print(round(kamica.shape[0] / gallstone.shape[0] *100, 2))
print(round(kontrola.shape[0] / gallstone.shape[0] *100, 2))

49.53
50.47

## Zadanie 7.

Obliczyć ilu jest pacjentów otyłych z kamicą nerkową. Porównać tę wartość z liczbą pacjentów otyłych w grupie kontrolnej.

In [23]:
sum(kamica["Obesity (%)"] >= 100)

2

In [24]:
sum(kontrola["Obesity (%)"] >= 100)

1

### drugi sposób

In [25]:
gallstone[gallstone["Obesity (%)"] >= 100].groupby("Gallstone Status").count()

,Age,Gender,Comorbidity,Coronary Artery Disease (CAD),Hypothyroidism,Hyperlipidemia,Diabetes Mellitus (DM),Height,Weight,Body Mass Index (BMI),...,High Density Lipoprotein (HDL),Triglyceride,Aspartat Aminotransferaz (AST),Alanin Aminotransferaz (ALT),Alkaline Phosphatase (ALP),Creatinine,Glomerular Filtration Rate (GFR),C-Reactive Protein (CRP),Hemoglobin (HGB),Vitamin D
Gallstone Status,,,,,,,,,,,,,,,,,,,,,
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2

## Zadanie 8.

Wybrać dane dotyczące nadwagi: ['Obesity (%)', 'Body Mass Index (BMI)', 'Weight', 'Total Body Fat Ratio (TBFR) (%)']. Obliczyć podstawowe statystyki: średnią, medianę i odchylenie standardowe i porównać je między grupą chorych i grupą kontrolną.

In [26]:
gallstone.groupby("Gallstone Status").agg({"Obesity (%)": ["mean", "median", "std"],
                                        "Body Mass Index (BMI)": ["mean", "median", "std"],
                                        "Weight": ["mean", "median", "std"],
                                        "Total Body Fat Ratio (TBFR) (%)": ["mean", "median", "std"]})

                 Obesity (%)                     Body Mass Index (BMI)         \
                        mean  median         std                  mean median
Gallstone Status
0                  29.994348  25.800   21.598417             28.238509  27.70
1                  41.817089  25.165  154.507974             29.527848  29.15

                               Weight                    \
                       std       mean median        std
Gallstone Status
0                 5.290523  79.808696  78.00  15.976226
1                 5.274610  81.335443  79.85  15.444613

                 Total Body Fat Ratio (TBFR) (%)
                                            mean median       std
Gallstone Status
0                                      26.391801  25.80  8.408398
1                                      30.193924  31.05  8.064643

## Zadanie 9.

Zidentyfikuj zmienne, które mają potencjalny wpływ na status kamicy nerkowej pacjenta:
* obliczyć średnią z każdej zmiennej w grupie kontrolnej i chorych oddzielnie,
* obliczyć różnicę w średnich między grupami,
* znormalizować wynik poprzez obliczenie wartości procentowej różnicy w stosunku do średniej w grupie kontrolnej,
* usunąć z wyniku zmienne binarne: ['Gender', 'Comorbidity', 'Coronary Artery Disease (CAD)', 'Hypothyroidism', 'Hyperlipidemia', 'Diabetes Mellitus (DM)'],
* zaindeksować wynik indeksem zmiennej posortowanej według wartości bezwzględnej.

In [27]:
gallstone.groupby("Gallstone Status").mean()

,Age,Gender,Comorbidity,Coronary Artery Disease (CAD),Hypothyroidism,Hyperlipidemia,Diabetes Mellitus (DM),Height,Weight,Body Mass Index (BMI),...,High Density Lipoprotein (HDL),Triglyceride,Aspartat Aminotransferaz (AST),Alanin Aminotransferaz (ALT),Alkaline Phosphatase (ALP),Creatinine,Glomerular Filtration Rate (GFR),C-Reactive Protein (CRP),Hemoglobin (HGB),Vitamin D
Gallstone Status,,,,,,,,,,,,,,,,,,,,,
0,47.633540,0.416149,0.360248,0.055901,0.037267,0.000000,0.099379,168.229814,79.808696,28.238509,...,46.695652,149.424783,23.913043,28.012422,70.484472,0.823696,101.293545,0.462174,14.763975,24.904969
1,48.512658,0.569620,0.310127,0.018987,0.018987,0.050633,0.170886,166.063291,81.335443,29.527848,...,52.308228,139.486076,19.414557,25.677215,75.790506,0.777089,100.335249,3.271962,14.065823,17.831329

In [28]:
srednia = gallstone.groupby("Gallstone Status").mean()
chop = srednia.loc[0] - srednia.loc[1]

In [29]:
proc = chop / srednia.loc[0] *100

In [30]:
proc

Age                                                -1.845586
Gender                                            -36.878897
Comorbidity                                        13.913138
Coronary Artery Disease (CAD)                      66.033755
Hypothyroidism                                     49.050633
Hyperlipidemia                                          -inf
Diabetes Mellitus (DM)                            -71.954114
Height                                              1.287835
Weight                                             -1.913009
Body Mass Index (BMI)                              -4.565888
Total Body Water (TBW)                              4.248682
Extracellular Water (ECW)                           6.390882
Intracellular Water (ICW)                           1.581849
Extracellular Fluid/Total Body Water (ECF/TBW)      2.573402
Total Body Fat Ratio (TBFR) (%)                   -14.406454
Lean Mass (LM) (%)                                  5.173612
Body Protein Content (Protein) (%)                  2.496793
Visceral Fat Rating (VFR)                          -1.758087
Bone Mass (BM)                                      7.565309
Muscle Mass (MM)                                    3.575652
Obesity (%)                                       -39.416562
Total Fat Content (TFC)                           -14.926909
Visceral Fat Area (VFA)                           -12.895287
Visceral Muscle Area (VMA) (Kg)                     2.115995
Hepatic Fat Accumulation (HFA)                    -18.082651
Glucose                                             0.943024
Total Cholesterol (TC)                             -0.635140
Low Density Lipoprotein (LDL)                       3.374177
High Density Lipoprotein (HDL)                    -12.019482
Triglyceride                                        6.651311
Aspartat Aminotransferaz (AST)                     18.811853
Alanin Aminotransferaz (ALT)                        8.336327
Alkaline Phosphatase (ALP)                         -7.527948
Creatinine                                          5.658285
Glomerular Filtration Rate (GFR)                    0.946058
C-Reactive Protein (CRP)                         -607.950391
Hemoglobin (HGB)                                    4.728756
Vitamin D                                          28.402524
dtype: float64

In [31]:
revcol = ['Gender', 'Comorbidity', 'Coronary Artery Disease (CAD)', 'Hypothyroidism', 'Hyperlipidemia', 'Diabetes Mellitus (DM)']
proc.drop(revcol, inplace=True)

In [32]:
proc

Age                                                -1.845586
Height                                              1.287835
Weight                                             -1.913009
Body Mass Index (BMI)                              -4.565888
Total Body Water (TBW)                              4.248682
Extracellular Water (ECW)                           6.390882
Intracellular Water (ICW)                           1.581849
Extracellular Fluid/Total Body Water (ECF/TBW)      2.573402
Total Body Fat Ratio (TBFR) (%)                   -14.406454
Lean Mass (LM) (%)                                  5.173612
Body Protein Content (Protein) (%)                  2.496793
Visceral Fat Rating (VFR)                          -1.758087
Bone Mass (BM)                                      7.565309
Muscle Mass (MM)                                    3.575652
Obesity (%)                                       -39.416562
Total Fat Content (TFC)                           -14.926909
Visceral Fat Area (VFA)                           -12.895287
Visceral Muscle Area (VMA) (Kg)                     2.115995
Hepatic Fat Accumulation (HFA)                    -18.082651
Glucose                                             0.943024
Total Cholesterol (TC)                             -0.635140
Low Density Lipoprotein (LDL)                       3.374177
High Density Lipoprotein (HDL)                    -12.019482
Triglyceride                                        6.651311
Aspartat Aminotransferaz (AST)                     18.811853
Alanin Aminotransferaz (ALT)                        8.336327
Alkaline Phosphatase (ALP)                         -7.527948
Creatinine                                          5.658285
Glomerular Filtration Rate (GFR)                    0.946058
C-Reactive Protein (CRP)                         -607.950391
Hemoglobin (HGB)                                    4.728756
Vitamin D                                          28.402524
dtype: float64

In [33]:
proc.reindex(proc.abs().sort_values(ascending=False).index)

C-Reactive Protein (CRP)                         -607.950391
Obesity (%)                                       -39.416562
Vitamin D                                          28.402524
Aspartat Aminotransferaz (AST)                     18.811853
Hepatic Fat Accumulation (HFA)                    -18.082651
Total Fat Content (TFC)                           -14.926909
Total Body Fat Ratio (TBFR) (%)                   -14.406454
Visceral Fat Area (VFA)                           -12.895287
High Density Lipoprotein (HDL)                    -12.019482
Alanin Aminotransferaz (ALT)                        8.336327
Bone Mass (BM)                                      7.565309
Alkaline Phosphatase (ALP)                         -7.527948
Triglyceride                                        6.651311
Extracellular Water (ECW)                           6.390882
Creatinine                                          5.658285
Lean Mass (LM) (%)                                  5.173612
Hemoglobin (HGB)                                    4.728756
Body Mass Index (BMI)                              -4.565888
Total Body Water (TBW)                              4.248682
Muscle Mass (MM)                                    3.575652
Low Density Lipoprotein (LDL)                       3.374177
Extracellular Fluid/Total Body Water (ECF/TBW)      2.573402
Body Protein Content (Protein) (%)                  2.496793
Visceral Muscle Area (VMA) (Kg)                     2.115995
Weight                                             -1.913009
Age                                                -1.845586
Visceral Fat Rating (VFR)                          -1.758087
Intracellular Water (ICW)                           1.581849
Height                                              1.287835
Glomerular Filtration Rate (GFR)                    0.946058
Glucose                                             0.943024
Total Cholesterol (TC)                             -0.635140
dtype: float64

## Zadanie 10.

Sprawdzić czy płeć ma wpływ na współczynnik zachorowania. Zbadać czy zmienne mają ten sam charakter w grupie kobiet i mężczyzn u chorych w stosunku do grupy kontrolnej:
* wyznaczyć liczbę kobiet i mężczyzn w grupie chorych i w kontroli, sprawdzić udział procentowy każdej płci w obu grupach,
* obliczyć średnią wartość każdej zmiennej wśród mężczyzn i kobiet w grupie chorych i kontrolnej,
* zidentyfikować zmienne, które u chorych mają odwrotną charakterystykę względem płciu niż w grupie kontrolnej.

In [34]:
pd.crosstab(gallstone["Gender"], gallstone["Gallstone Status"], normalize="columns")

Gallstone Status         0        1
Gender
0                 0.583851  0.43038
1                 0.416149  0.56962

In [35]:
gallstone.groupby(["Gallstone Status", "Gender"]).mean().diff().loc[[(0,1), (1,1)]].T

Gallstone Status                                        0          1
Gender                                                  1          1
Age                                              1.343442   2.655556
Comorbidity                                     -0.054621   0.002288
Coronary Artery Disease (CAD)                   -0.019054  -0.044118
Hypothyroidism                                   0.089552   0.007516
Hyperlipidemia                                   0.000000   0.088889
Diabetes Mellitus (DM)                          -0.042394  -0.087255
Height                                         -14.197999 -14.966013
Weight                                         -10.828326 -11.245621
Body Mass Index (BMI)                            1.030724   1.285523
Total Body Water (TBW)                         -11.773007 -11.684412
Extracellular Water (ECW)                       -3.820641  -4.869804
Intracellular Water (ICW)                       -7.948126  -7.974542
Extracellular Fluid/Total Body Water (ECF/TBW)   2.831426   0.540252
Total Body Fat Ratio (TBFR) (%)                  9.958055  10.296510
Lean Mass (LM) (%)                             -10.149284 -10.176886
Body Protein Content (Protein) (%)              -1.760360  -1.525265
Visceral Fat Rating (VFR)                       -2.914258  -2.949346
Bone Mass (BM)                                  -0.752398  -0.562500
Muscle Mass (MM)                               -15.314020 -16.288856
Obesity (%)                                      5.624741  27.682582
Total Fat Content (TFC)                          4.845745   5.566405
Visceral Fat Area (VFA)                         -1.273282  -1.105696
Visceral Muscle Area (VMA) (Kg)                 -6.564909  -4.915977
Hepatic Fat Accumulation (HFA)                  -0.172436  -0.315359
Glucose                                         -5.376469 -13.494771
Total Cholesterol (TC)                           3.184503  11.331046
Low Density Lipoprotein (LDL)                   -2.682471   2.961275
High Density Lipoprotein (HDL)                  12.638457  12.437582
Triglyceride                                   -59.539590 -21.163399
Aspartat Aminotransferaz (AST)                  -7.392347  -6.797876
Alanin Aminotransferaz (ALT)                   -16.739917 -17.954412
Alkaline Phosphatase (ALP)                       5.024293  -4.495915
Creatinine                                      -0.255192  -0.185572
Glomerular Filtration Rate (GFR)                 2.834564  -0.880473
C-Reactive Protein (CRP)                         0.658759   0.583294
Hemoglobin (HGB)                                -2.469101  -2.313824
Vitamin D                                       -0.858929  -0.972516