# Ćwiczenia 1: Wprowadzenie do analizy danych tabelarycznych

## Zadanie 1.

Zaimportować stałą `pi` z modułu `math`. Obliczyć pole koła o promieniu $r=7$ wykorzystując stałą `pi` z modułu `math`.

In [1]:
import math #import całego modułu
math.pi #odnoszenie się do metod modułu math

3.141592653589793

In [2]:
from math import pi #import danej rzeczy z modułu
pi #wyświetli liczbę pi

3.141592653589793

In [3]:
r = 7 #promień
pi*r**2 #wzór na pole koła

153.93804002589985

## Zadanie 2.

Zaimportować funkcję `randint` z modułu `random` i nazwać ją `losuj_zakres`. Napisać program, który wykorzysta tę funkcję do wylosowania numeru studenta, który pójdzie do tablicy.

In [4]:
import random
random.randint(5,10) #postawienie pytajnika przed funkcją pozwala na wyświetlenie jej dokumentacji

5

In [5]:
from random import randint as losuj_zakres #importowanie jednej funkcji i nadawanie jej nazwy
num_studenta = losuj_zakres(1,11) #w ten sposób nie wystąpi błąd (do tablicy idzie i wstaje ten sam student)
print(f'do tablicy idzie student o numerze {num_studenta}')
print(f'student o numerze {num_studenta} wstaje z krzesła')
#bez przypisania randint(zakres) do jednej zmiennej to funkcja dwa razy wylosuje numery

do tablicy idzie student o numerze 4
student o numerze 4 wstaje z krzesła

## Zadanie 3.

Zaimportować moduł `pandas` i przypisać mu nazwę `pd`. Wypisać wersję aktualnie zainstalowanego modułu Pandas.

In [6]:
pip install pandas

Requirement already satisfied: pandas in /home/oligus/miniconda3/envs/pp/lib/python3.14/site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in /home/oligus/miniconda3/envs/pp/lib/python3.14/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/oligus/miniconda3/envs/pp/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/oligus/miniconda3/envs/pp/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
pd.__version__

'3.0.1'

## Zadanie 4.

Wykorzystując moduł Pandas wczytać zestaw danych gallstone. Wyświetlić krótką próbkę danych metodą `.head()`, opis kolumn metodą `.info()` oraz podstawowe statystki tego zbioru danych metodą `.descrbie()`. Transponuj wynik `.describe()` dla lepszej czytelności.

In [8]:
gallstone = pd.read_csv("DATA/gallstone.csv")

In [43]:
gallstone.head() #wyświetla kilka pierwszych wierszy (parametr n określa ilość wierszy)
#gallstone.tail() wyświetla kilka ostatnich wierszy

,Gallstone Status,Age,Gender,Comorbidity,Coronary Artery Disease (CAD),Hypothyroidism,Hyperlipidemia,Diabetes Mellitus (DM),Height,Weight,...,High Density Lipoprotein (HDL),Triglyceride,Aspartat Aminotransferaz (AST),Alanin Aminotransferaz (ALT),Alkaline Phosphatase (ALP),Creatinine,Glomerular Filtration Rate (GFR),C-Reactive Protein (CRP),Hemoglobin (HGB),Vitamin D
0,0,50,0,0,0,0,0,0,185,92.8,...,40.0,134.0,20.0,22.0,87.0,0.82,112.47,0.0,16.0,33.0
1,0,47,0,1,0,0,0,0,176,94.5,...,43.0,103.0,14.0,13.0,46.0,0.87,107.10,0.0,14.4,25.0
2,0,61,0,0,0,0,0,0,171,91.1,...,43.0,69.0,18.0,14.0,66.0,1.25,65.51,0.0,16.2,30.2
3,0,41,0,0,0,0,0,0,168,67.7,...,59.0,53.0,20.0,12.0,34.0,1.02,94.10,0.0,15.4,35.4
4,0,42,0,0,0,0,0,0,178,89.6,...,30.0,326.0,27.0,54.0,71.0,0.82,112.47,0.0,16.8,40.6

In [48]:
gallstone.info() #wypisuje skompresowane kolumny z pliku, info o typach danych i NA,

<class 'pandas.DataFrame'>
RangeIndex: 319 entries, 0 to 318
Data columns (total 39 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Gallstone Status                                319 non-null    int64
 1   Age                                             319 non-null    int64
 2   Gender                                          319 non-null    int64
 3   Comorbidity                                     319 non-null    int64
 4   Coronary Artery Disease (CAD)                   319 non-null    int64
 5   Hypothyroidism                                  319 non-null    int64
 6   Hyperlipidemia                                  319 non-null    int64
 7   Diabetes Mellitus (DM)                          319 non-null    int64
 8   Height                                          319 non-null    int64
 9   Weight                                          319 non-null    float64
 10  Body Mass Index (BMI)                           319 non-null    float64
 11  Total Body Water (TBW)                          319 non-null    float64
 12  Extracellular Water (ECW)                       319 non-null    float64
 13  Intracellular Water (ICW)                       319 non-null    float64
 14  Extracellular Fluid/Total Body Water (ECF/TBW)  319 non-null    float64
 15  Total Body Fat Ratio (TBFR) (%)                 319 non-null    float64
 16  Lean Mass (LM) (%)                              319 non-null    float64
 17  Body Protein Content (Protein) (%)              319 non-null    float64
 18  Visceral Fat Rating (VFR)                       319 non-null    int64
 19  Bone Mass (BM)                                  319 non-null    float64
 20  Muscle Mass (MM)                                319 non-null    float64
 21  Obesity (%)                                     319 non-null    float64
 22  Total Fat Content (TFC)                         319 non-null    float64
 23  Visceral Fat Area (VFA)                         319 non-null    float64
 24  Visceral Muscle Area (VMA) (Kg)                 319 non-null    float64
 25  Hepatic Fat Accumulation (HFA)                  319 non-null    int64
 26  Glucose                                         319 non-null    float64
 27  Total Cholesterol (TC)                          319 non-null    float64
 28  Low Density Lipoprotein (LDL)                   319 non-null    float64
 29  High Density Lipoprotein (HDL)                  319 non-null    float64
 30  Triglyceride                                    319 non-null    float64
 31  Aspartat Aminotransferaz (AST)                  319 non-null    float64
 32  Alanin Aminotransferaz (ALT)                    319 non-null    float64
 33  Alkaline Phosphatase (ALP)                      319 non-null    float64
 34  Creatinine                                      319 non-null    float64
 35  Glomerular Filtration Rate (GFR)                319 non-null    float64
 36  C-Reactive Protein (CRP)                        319 non-null    float64
 37  Hemoglobin (HGB)                                319 non-null    float64
 38  Vitamin D                                       319 non-null    float64
dtypes: float64(28), int64(11)
memory usage: 97.3 KB

In [57]:
gallstone.describe() #podstawowe statystyki zbioru

,Gallstone Status,Age,Gender,Comorbidity,Coronary Artery Disease (CAD),Hypothyroidism,Hyperlipidemia,Diabetes Mellitus (DM),Height,Weight,...,High Density Lipoprotein (HDL),Triglyceride,Aspartat Aminotransferaz (AST),Alanin Aminotransferaz (ALT),Alkaline Phosphatase (ALP),Creatinine,Glomerular Filtration Rate (GFR),C-Reactive Protein (CRP),Hemoglobin (HGB),Vitamin D
count,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.00000,319.000000,...,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000
mean,0.495298,48.068966,0.492163,0.335423,0.037618,0.028213,0.025078,0.134796,167.15674,80.564890,...,49.475549,144.502163,21.684953,26.855799,73.112539,0.800611,100.818903,1.853856,14.418182,21.401411
std,0.500763,12.114558,0.500724,0.517340,0.190568,0.165841,0.156609,0.342042,10.05303,15.709069,...,17.718701,97.904493,16.697605,27.884413,24.181069,0.176433,16.971396,4.989591,1.775815,9.981659
min,0.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,145.00000,42.900000,...,25.000000,1.390000,8.000000,3.000000,7.000000,0.460000,10.600000,0.000000,8.500000,3.500000
25%,0.000000,38.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,159.50000,69.600000,...,40.000000,83.000000,15.000000,14.250000,58.000000,0.650000,94.170000,0.000000,13.300000,13.250000
50%,0.000000,49.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,168.00000,78.800000,...,46.500000,119.000000,18.000000,19.000000,71.000000,0.790000,104.000000,0.215000,14.400000,22.000000
75%,1.000000,56.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,175.00000,91.250000,...,56.000000,172.000000,23.000000,30.000000,86.000000,0.920000,110.745000,1.615000,15.700000,28.060000
max,1.000000,96.000000,1.000000,3.000000,1.000000,1.000000,1.000000,1.000000,191.00000,143.500000,...,273.000000,838.000000,195.000000,372.000000,197.000000,1.460000,132.000000,43.400000,18.800000,53.100000

In [13]:
gallstone.describe().T #inny sposob na transpozycję tabeli

,count,mean,std,min,25%,50%,75%,max
Gallstone Status,319.0,0.495298,0.500763,0.00,0.000,0.000000,1.000,1.00
Age,319.0,48.068966,12.114558,20.00,38.500,49.000000,56.000,96.00
Gender,319.0,0.492163,0.500724,0.00,0.000,0.000000,1.000,1.00
Comorbidity,319.0,0.335423,0.517340,0.00,0.000,0.000000,1.000,3.00
Coronary Artery Disease (CAD),319.0,0.037618,0.190568,0.00,0.000,0.000000,0.000,1.00
Hypothyroidism,319.0,0.028213,0.165841,0.00,0.000,0.000000,0.000,1.00
Hyperlipidemia,319.0,0.025078,0.156609,0.00,0.000,0.000000,0.000,1.00
Diabetes Mellitus (DM),319.0,0.134796,0.342042,0.00,0.000,0.000000,0.000,1.00
Height,319.0,167.156740,10.053030,145.00,159.500,168.000000,175.000,191.00
Weight,319.0,80.564890,15.709069,42.90,69.600,78.800000,91.250,143.50
Body Mass Index (BMI),319.0,28.877116,5.313707,17.40,25.250,28.300000,31.850,49.70
Total Body Water (TBW),319.0,40.587774,7.930235,13.00,34.200,39.800000,47.000,66.20
Extracellular Water (ECW),319.0,17.071160,3.161857,9.00,14.800,17.100000,19.400,27.80
Intracellular Water (ICW),319.0,23.634483,5.349332,13.80,19.300,23.000000,27.550,57.10
Extracellular Fluid/Total Body Water (ECF/TBW),319.0,42.212038,3.244470,29.23,40.075,42.000000,44.000,52.00
Total Body Fat Ratio (TBFR) (%),319.0,28.274984,8.444417,6.30,22.025,27.820000,34.810,50.92
Lean Mass (LM) (%),319.0,71.638245,8.437598,48.99,65.165,72.110000,77.850,93.67
Body Protein Content (Protein) (%),319.0,15.938809,2.334744,5.56,14.465,15.870000,17.430,24.81
Visceral Fat Rating (VFR),319.0,9.078370,4.332501,1.00,6.000,9.000000,12.000,31.00
Bone Mass (BM),319.0,2.803292,0.509467,1.40,2.400,2.800000,3.200,4.00
Muscle Mass (MM),319.0,54.273041,10.603833,4.70,45.800,53.900000,62.600,78.80
Obesity (%),319.0,35.850125,109.799718,0.40,13.900,25.600000,41.750,1954.00
Total Fat Content (TFC),319.0,23.487774,9.607607,3.10,17.000,22.600000,28.550,62.50
Visceral Fat Area (VFA),319.0,12.171599,5.262178,0.90,8.570,11.590000,15.100,41.00
Visceral Muscle Area (VMA) (Kg),319.0,30.403448,4.460530,18.90,27.250,30.408108,33.800,41.10
Hepatic Fat Accumulation (HFA),319.0,1.150470,1.059217,0.00,0.000,1.000000,2.000,4.00
Glucose,319.0,108.688715,44.848714,69.00,92.000,98.000000,109.000,575.00
Total Cholesterol (TC),319.0,203.495298,45.758501,60.00,172.000,198.000000,233.000,360.00
Low Density Lipoprotein (LDL),319.0,126.652351,38.541175,11.00,100.500,122.000000,151.000,293.00
High Density Lipoprotein (HDL),319.0,49.475549,17.718701,25.00,40.000,46.500000,56.000,273.00
Triglyceride,319.0,144.502163,97.904493,1.39,83.000,119.000000,172.000,838.00
Aspartat Aminotransferaz (AST),319.0,21.684953,16.697605,8.00,15.000,18.000000,23.000,195.00
Alanin Aminotransferaz (ALT),319.0,26.855799,27.884413,3.00,14.250,19.000000,30.000,372.00
Alkaline Phosphatase (ALP),319.0,73.112539,24.181069,7.00,58.000,71.000000,86.000,197.00
Creatinine,319.0,0.800611,0.176433,0.46,0.650,0.790000,0.920,1.46
Glomerular Filtration Rate (GFR),319.0,100.818903,16.971396,10.60,94.170,104.000000,110.745,132.00
C-Reactive Protein (CRP),319.0,1.853856,4.989591,0.00,0.000,0.215000,1.615,43.40
Hemoglobin (HGB),319.0,14.418182,1.775815,8.50,13.300,14.400000,15.700,18.80
Vitamin D,319.0,21.401411,9.981659,3.50,13.250,22.000000,28.060,53.10

## Zadanie 5.

Oczyścić dane z nieprawidłowych wartości:
1. sprawdzić czy wczytany zestaw danych posiada wartości brakujące. Jeśli tak to należy usunąć wiersze zawierające braki.
2. analizując tabelę z powyższego zadania zidentyfikować nieprawidłowy wiersz
3. analizując układ zmiennych dotyczących zawartości wody w organizmie zidentyfikować nieprawidłowe dane $(\text{ECW} + \text{ICW} \approx \text{TBW})$
4. analizując układ zmiennych masy mięśniowej, beztłuszczowej masy ciała i wagi zidentyfikować nieprawidłowe dane
5. korzystając z [wzoru Friedewalda](https://pl.wikipedia.org/wiki/Wz%C3%B3r_Friedewalda): $\text{LDL} \approx \text{TC} − \text{HDL} − \text{TG}/5$ zidentyfikować wiersze o niespójnym profilu lipidowym
6. analizując tabelę z powyższego zadania sprawdź czy na pewno wszystkie wiersze zawierają poprawną wartość triglicerydów.
7. usunąć zidentyfikowane wiersze ze zbioru danych.

In [62]:
#1 - NA
gallstone.isna().sum().sum() #wyświetla kolumny F/T dla brakujących wartości (.sum sumuje wszystkie te wartosci 0-f i 1-p)
#podwojnie zsumowane wyświetla łaczna ilość F(0)
#co zwraca dana metoda  → co mozna jeszcze wywołać na podstawie wyniku

np.int64(0)

In [ ]:
#2 - nieprawidłowy wiersz z zadania 4
gallstone["Obesity (%)"].nlargest() #wypisuje daną kolumnę z dataframe
#nlargest pokazuje najwyższą wartość (1954 to wartosc nieprawidłowa)

239    1954.00
23      125.60
209     106.30
280      96.63
246      95.64
Name: Obesity (%), dtype: float64

In [ ]:
#3 - zawartość wody nieprawidłowe dane
(gallstone["Extracellular Water (ECW)"] + gallstone["Intracellular Water (ICW)"] - gallstone["Total Body Water (TBW)"]).abs().nlargest()

178    62.6
168    14.7
300    10.0
60      1.0
268     0.5
dtype: float64

In [ ]:
#4 - masa mięśniowa, beztłuszczowa masa i waga, nieprawidłowe dane
gallstone["Muscle Mass (MM)"].nsmallest()

205     4.7
261    32.8
135    34.6
300    35.0
233    36.2
Name: Muscle Mass (MM), dtype: float64

In [ ]:
#4 - masa mięśniowa, beztłuszczowa masa i waga, nieprawidłowe dane
gallstone.columns #wyświetla nazwy kolumn
gallstone.loc[205,["Muscle Mass (MM)", "Lean Mass (LM) (%)", "Weight"]] #podwójny nawias bo lista i odwołanie do kolumn
#numer miedzy nawiasami mowi o wyswietlanej kolumnie

Muscle Mass (MM)       4.70
Lean Mass (LM) (%)    63.14
Weight                78.40
Name: 205, dtype: float64

In [ ]:
#5 - niespójny charakter lipidowy
gallstone.columns
LDL = gallstone["Total Cholesterol (TC)"] - gallstone["High Density Lipoprotein (HDL)"] - gallstone["Triglyceride"]/5
#obliczenie oczekiwanej wartości LDL ze wzoru
(gallstone["Low Density Lipoprotein (LDL)"] - LDL).abs().nlargest(n=10)
#oblicznie różnicy między oczekiwaną a rzeczywistą wartością
gallstone.loc[[194,318],["Total Cholesterol (TC)", "High Density Lipoprotein (HDL)", "Triglyceride", "Low Density Lipoprotein (LDL)"]]
#wyświetlenie kolumn z danymi o lipidach z wierszy o niespójnym profilu

,Total Cholesterol (TC),High Density Lipoprotein (HDL),Triglyceride,Low Density Lipoprotein (LDL)
194,280.0,30.0,116.0,88.0
318,296.0,273.0,19.0,155.0

In [ ]:
#6 - poprawna wartość triglicerydów (TG =< 400 mg/dL)
gallstone["Triglyceride"].nlargest(n=10)

242    838.0
20     692.0
8      679.0
7      464.0
50     455.0
271    391.0
65     388.0
81     377.0
49     375.0
199    350.0
Name: Triglyceride, dtype: float64

In [ ]:
#7 - usunięcie nieprawidłowych wierszy (239, 318, 194, 205, 242, 20, 8, 7, 50 ??)

## Zadanie 6.

Obliczyć udział procentowy pacjentów z kamicą nerkową i zdrowych (zmienna *Gallstone Status*). Do zmiennej `kamica` przypisać wiersze pacjentów, którzy mają kamicę $(\text{Gallstone Status}=1)$. Do zmiennej `kontrola` przypisać pacjentów, którzy nie mają kamicy $(\text{Gallstone Status}=0)$.

## Zadanie 7.

Obliczyć ilu jest pacjentów otyłych z kamicą nerkową. Porównać tę wartość z liczbą pacjentów otyłych w grupie kontrolnej.

### drugi sposób

## Zadanie 8.

Wybrać dane dotyczące nadwagi: ['Obesity (%)', 'Body Mass Index (BMI)', 'Weight', 'Total Body Fat Ratio (TBFR) (%)']. Obliczyć podstawowe statystyki: średnią, medianę i odchylenie standardowe i porównać je między grupą chorych i grupą kontrolną.

## Zadanie 9.

Zidentyfikuj zmienne, które mają potencjalny wpływ na status kamicy nerkowej pacjenta:
* obliczyć średnią z każdej zmiennej w grupie kontrolnej i chorych oddzielnie,
* obliczyć różnicę w średnich między grupami,
* znormalizować wynik poprzez obliczenie wartości procentowej różnicy w stosunku do średniej w grupie kontrolnej,
* usunąć z wyniku zmienne binarne: ['Gender', 'Comorbidity', 'Coronary Artery Disease (CAD)', 'Hypothyroidism', 'Hyperlipidemia', 'Diabetes Mellitus (DM)'],
* zaindeksować wynik indeksem zmiennej posortowanej według wartości bezwzględnej.

## Zadanie 10.

Sprawdzić czy płeć ma wpływ na współczynnik zachorowania. Zbadać czy zmienne mają ten sam charakter w grupie kobiet i mężczyzn u chorych w stosunku do grupy kontrolnej:
* wyznaczyć liczbę kobiet i mężczyzn w grupie chorych i w kontroli, sprawdzić udział procentowy każdej płci w obu grupach,
* obliczyć średnią wartość każdej zmiennej wśród mężczyzn i kobiet w grupie chorych i kontrolnej,
* zidentyfikować zmienne, które u chorych mają odwrotną charakterystykę względem płciu niż w grupie kontrolnej.